name: Update Messages

on:
  repository_dispatch:
    types: [update-messages]

jobs:
  append-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure messages.json exists
        run: |
          if [ ! -f messages.json ]; then
            echo "[]" > messages.json
          fi

      - name: Append encrypted message
        run: |
          CURRENT=$(cat messages.json)
          NEW="${{ github.event.client_payload.encrypted }}"
          UPDATED=$(echo "$CURRENT" | jq --arg msg "$NEW" '. += [$msg]')
          echo "$UPDATED" > messages.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add messages.json
          git commit -m "Add encrypted message [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
